AWSTemplateFormatVersion: '2010-09-09'
Description: Template para criação de um bucket S3

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "my-unique-bucket-name"  # Escolha um nome único para o seu bucket

Outputs:
  BucketName:
    Description: "Nome do bucket S3"
    Value: !Ref MyS3Bucket
  BucketArn:
    Description: "ARN do bucket S3"
    Value: !GetAtt MyS3Bucket.Arn

# Este template cria o seguinte recurso:
# - Bucket S3
